- name: Set up Git authentication
  run: |
    git config --global user.name "github-actions[bot]"
    git config --global user.email "github-actions[bot]@users.noreply.github.com"
    git remote set-url origin https://github.com/${{ github.repository }}.git
- name: Push changes
  env:
    GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  run: |
    git add .
    git commit -m "Automated commit"
    git push origin main
